"""Archetype classification for every entry in
:data:`ts_shape.eventlog.taxonomy.REGISTRY`.

Each detector method belongs to exactly one of eight conceptual archetypes
that share a common attribute fingerprint. The archetype determines which
keys in :data:`ts_shape.eventlog.schema.STANDARD_ATTR_KEYS` are *required*
for the method's ``LabelRule.standard_attrs`` mapping (enforced by
``tests/eventlog/test_adapter_coverage.py``).

The eight archetypes:

============== ==============================================================
threshold      Reading vs. reference: outlier, SPC, tolerance, threshold,
               drift, exceedance.
interval       Start/end + state label: run/idle, alarm windows, startups,
               warmup intervals, gaps.
aggregate      Windowed KPI / statistics: per-shift, per-day, per-part roll-ups.
outcome        Categorical record: scrap reason, NOK reason, transition labels.
static         Single-row reference data: gauge R&R, control limits, top-N
               reasons, current status snapshots.
trace          Multi-station path / handover timeline.
forecast       Future / projected value: RUL, capability forecast, stockout.
correlation    Cross-signal pair metric: lag, rolling correlation, cascade.
============== ==============================================================
"""

from __future__ import annotations

ARCHETYPE_BY_METHOD: dict[tuple[str, str], str] = {
    # ---- correlation -------------------------------------------------------
    ("AnomalyCorrelationEvents", "cascade_detection"): "correlation",
    ("AnomalyCorrelationEvents", "coincident_anomalies"): "correlation",
    ("AnomalyCorrelationEvents", "root_cause_ranking"): "correlation",
    ("SignalCorrelationEvents", "correlation_breakdown"): "correlation",
    ("SignalCorrelationEvents", "lag_correlation"): "correlation",
    ("SignalCorrelationEvents", "rolling_correlation"): "correlation",
    # ---- energy ------------------------------------------------------------
    ("CarbonIntensityEvents", "carbon_intensity_per_unit"): "aggregate",
    ("CarbonIntensityEvents", "emission_factor_audit"): "aggregate",
    ("CarbonIntensityEvents", "emissions_by_window"): "aggregate",
    ("CarbonIntensityEvents", "total_emissions_by_window"): "aggregate",
    ("EnergyConsumptionEvents", "consumption_baseline_deviation"): "threshold",
    ("EnergyConsumptionEvents", "consumption_by_window"): "aggregate",
    ("EnergyConsumptionEvents", "energy_per_unit"): "aggregate",
    ("EnergyConsumptionEvents", "normalize"): "aggregate",
    ("EnergyConsumptionEvents", "peak_demand_detection"): "threshold",
    ("EnergyEfficiencyEvents", "efficiency_comparison"): "aggregate",
    ("EnergyEfficiencyEvents", "efficiency_trend"): "aggregate",
    ("EnergyEfficiencyEvents", "idle_energy_waste"): "aggregate",
    ("EnergyEfficiencyEvents", "normalize"): "aggregate",
    ("EnergyEfficiencyEvents", "specific_energy_consumption"): "aggregate",
    ("EnergyPerformanceIndicatorEvents", "enpi_by_hierarchy"): "aggregate",
    ("EnergyPerformanceIndicatorEvents", "enpi_by_window"): "aggregate",
    ("EnergyPerformanceIndicatorEvents", "enpi_vs_baseline"): "threshold",
    ("IdleEnergyDetectionEvents", "idle_energy_by_shift"): "aggregate",
    ("IdleEnergyDetectionEvents", "idle_energy_by_window"): "aggregate",
    ("IdleEnergyDetectionEvents", "idle_energy_trend"): "aggregate",
    # ---- engineering -------------------------------------------------------
    ("ControlLoopHealthEvents", "detect_oscillation"): "interval",
    ("ControlLoopHealthEvents", "error_integrals"): "aggregate",
    ("ControlLoopHealthEvents", "loop_health_summary"): "aggregate",
    ("ControlLoopHealthEvents", "output_saturation"): "interval",
    ("DisturbanceRecoveryEvents", "before_after_comparison"): "aggregate",
    ("DisturbanceRecoveryEvents", "detect_disturbances"): "threshold",
    ("DisturbanceRecoveryEvents", "disturbance_frequency"): "aggregate",
    ("DisturbanceRecoveryEvents", "recovery_time"): "interval",
    ("MaterialBalanceEvents", "balance_check"): "aggregate",
    ("MaterialBalanceEvents", "contribution_breakdown"): "aggregate",
    ("MaterialBalanceEvents", "detect_balance_exceedance"): "threshold",
    ("MaterialBalanceEvents", "imbalance_trend"): "aggregate",
    ("OperatingRangeEvents", "detect_regime_change"): "outcome",
    ("OperatingRangeEvents", "operating_envelope"): "aggregate",
    ("OperatingRangeEvents", "time_in_range"): "aggregate",
    ("OperatingRangeEvents", "value_distribution"): "aggregate",
    ("ProcessStabilityIndex", "score_trend"): "aggregate",
    ("ProcessStabilityIndex", "stability_comparison"): "aggregate",
    ("ProcessStabilityIndex", "stability_score"): "aggregate",
    ("ProcessStabilityIndex", "worst_periods"): "aggregate",
    ("ProcessWindowEvents", "detect_mean_shift"): "threshold",
    ("ProcessWindowEvents", "detect_variance_change"): "threshold",
    ("ProcessWindowEvents", "window_comparison"): "aggregate",
    ("ProcessWindowEvents", "windowed_statistics"): "aggregate",
    ("RateOfChangeEvents", "detect_rapid_change"): "threshold",
    ("RateOfChangeEvents", "detect_step_changes"): "threshold",
    ("RateOfChangeEvents", "rate_statistics"): "aggregate",
    ("SetpointChangeEvents", "control_quality_metrics"): "aggregate",
    ("SetpointChangeEvents", "decay_rate"): "aggregate",
    ("SetpointChangeEvents", "detect_setpoint_changes"): "outcome",
    ("SetpointChangeEvents", "detect_setpoint_ramps"): "interval",
    ("SetpointChangeEvents", "detect_setpoint_steps"): "interval",
    ("SetpointChangeEvents", "oscillation_frequency"): "aggregate",
    ("SetpointChangeEvents", "overshoot_metrics"): "aggregate",
    ("SetpointChangeEvents", "rise_time"): "aggregate",
    ("SetpointChangeEvents", "time_to_settle"): "aggregate",
    ("SetpointChangeEvents", "time_to_settle_derivative"): "aggregate",
    ("SignalComparisonEvents", "correlation_windows"): "correlation",
    ("SignalComparisonEvents", "detect_divergence"): "threshold",
    ("SignalComparisonEvents", "deviation_statistics"): "aggregate",
    ("SignalComparisonEvents", "tracking_error_trend"): "aggregate",
    ("StartupDetectionEvents", "assess_startup_quality"): "aggregate",
    ("StartupDetectionEvents", "detect_failed_startups"): "outcome",
    ("StartupDetectionEvents", "detect_startup_adaptive"): "interval",
    ("StartupDetectionEvents", "detect_startup_by_slope"): "interval",
    ("StartupDetectionEvents", "detect_startup_by_threshold"): "interval",
    ("StartupDetectionEvents", "detect_startup_multi_signal"): "interval",
    ("StartupDetectionEvents", "track_startup_phases"): "interval",
    ("SteadyStateDetectionEvents", "detect_steady_state"): "interval",
    ("SteadyStateDetectionEvents", "detect_transient_periods"): "interval",
    ("SteadyStateDetectionEvents", "steady_state_value_bands"): "aggregate",
    ("ThresholdMonitoringEvents", "multi_level_threshold"): "threshold",
    ("ThresholdMonitoringEvents", "threshold_exceedance_trend"): "aggregate",
    ("ThresholdMonitoringEvents", "threshold_with_hysteresis"): "threshold",
    ("ThresholdMonitoringEvents", "time_above_threshold"): "aggregate",
    ("WarmUpCoolDownEvents", "detect_cooldown"): "interval",
    ("WarmUpCoolDownEvents", "detect_warmup"): "interval",
    ("WarmUpCoolDownEvents", "time_to_target"): "aggregate",
    ("WarmUpCoolDownEvents", "warmup_consistency"): "aggregate",
    # ---- maintenance -------------------------------------------------------
    ("DegradationDetectionEvents", "detect_level_shift"): "threshold",
    ("DegradationDetectionEvents", "detect_trend_degradation"): "interval",
    ("DegradationDetectionEvents", "detect_variance_increase"): "interval",
    ("DegradationDetectionEvents", "health_score"): "aggregate",
    ("FailurePredictionEvents", "detect_exceedance_pattern"): "threshold",
    ("FailurePredictionEvents", "remaining_useful_life"): "forecast",
    ("FailurePredictionEvents", "time_to_threshold"): "forecast",
    ("VibrationAnalysisEvents", "bearing_health_indicators"): "aggregate",
    ("VibrationAnalysisEvents", "detect_amplitude_growth"): "threshold",
    ("VibrationAnalysisEvents", "detect_rms_exceedance"): "threshold",
    # ---- production --------------------------------------------------------
    ("AlarmManagementEvents", "alarm_duration_stats"): "aggregate",
    ("AlarmManagementEvents", "alarm_frequency"): "aggregate",
    ("AlarmManagementEvents", "chattering_detection"): "interval",
    ("AlarmManagementEvents", "standing_alarms"): "interval",
    ("BatchTrackingEvents", "batch_duration_stats"): "aggregate",
    ("BatchTrackingEvents", "batch_transition_matrix"): "static",
    ("BatchTrackingEvents", "batch_yield"): "aggregate",
    ("BatchTrackingEvents", "detect_batches"): "interval",
    ("BottleneckDetectionEvents", "detect_bottleneck"): "outcome",
    ("BottleneckDetectionEvents", "shifting_bottleneck"): "aggregate",
    ("BottleneckDetectionEvents", "station_utilization"): "aggregate",
    ("ChangeoverEvents", "changeover_quality_metrics"): "aggregate",
    ("ChangeoverEvents", "changeover_window"): "interval",
    ("ChangeoverEvents", "detect_changeover"): "interval",
    ("ContinuousProcessAlignmentEvents", "align_to_reference"): "aggregate",
    ("ContinuousProcessAlignmentEvents", "alignment_quality"): "aggregate",
    ("ContinuousProcessAlignmentEvents", "lag_profile"): "aggregate",
    ("ContinuousProcessAlignmentEvents", "segment_by_cut"): "interval",
    ("CycleTimeTracking", "cycle_time_by_part"): "aggregate",
    ("CycleTimeTracking", "cycle_time_statistics"): "aggregate",
    ("CycleTimeTracking", "cycle_time_trend"): "aggregate",
    ("CycleTimeTracking", "detect_slow_cycles"): "threshold",
    ("CycleTimeTracking", "hourly_cycle_time_summary"): "aggregate",
    ("DowntimeTracking", "availability_trend"): "aggregate",
    ("DowntimeTracking", "downtime_by_reason"): "outcome",
    ("DowntimeTracking", "downtime_by_shift"): "aggregate",
    ("DowntimeTracking", "top_downtime_reasons"): "static",
    ("DutyCycleEvents", "cycle_count"): "aggregate",
    ("DutyCycleEvents", "duty_cycle_per_window"): "aggregate",
    ("DutyCycleEvents", "excessive_cycling"): "threshold",
    ("DutyCycleEvents", "on_off_intervals"): "interval",
    ("FlowConstraintEvents", "blocked_events"): "interval",
    ("FlowConstraintEvents", "starved_events"): "interval",
    ("FlowMetricsEvents", "flow_summary"): "aggregate",
    ("FlowMetricsEvents", "lead_time"): "aggregate",
    ("FlowMetricsEvents", "throughput"): "aggregate",
    ("FlowMetricsEvents", "wip_over_time"): "aggregate",
    ("LineBalancingEvents", "balance_metrics"): "aggregate",
    ("LineBalancingEvents", "station_cycle_times"): "aggregate",
    ("LineBalancingEvents", "yamazumi"): "static",
    ("LineThroughputEvents", "count_parts"): "aggregate",
    ("LineThroughputEvents", "cycle_quality_check"): "outcome",
    ("LineThroughputEvents", "takt_adherence"): "aggregate",
    ("LineThroughputEvents", "throughput_oee"): "aggregate",
    ("LineThroughputEvents", "throughput_trends"): "aggregate",
    ("LongDowntimeEvents", "count_events_between_gaps"): "aggregate",
    ("LongDowntimeEvents", "detect_long_downtime"): "interval",
    ("MachineStateEvents", "detect_rapid_transitions"): "threshold",
    ("MachineStateEvents", "detect_run_idle"): "interval",
    ("MachineStateEvents", "transition_events"): "outcome",
    ("MicroStopEvents", "detect_micro_stops"): "interval",
    ("MicroStopEvents", "micro_stop_frequency"): "aggregate",
    ("MicroStopEvents", "micro_stop_impact"): "aggregate",
    ("MicroStopEvents", "micro_stop_patterns"): "aggregate",
    ("MultiProcessTraceabilityEvents", "build_timeline"): "trace",
    ("MultiProcessTraceabilityEvents", "handover_log"): "trace",
    ("MultiProcessTraceabilityEvents", "lead_time"): "aggregate",
    ("MultiProcessTraceabilityEvents", "parallel_activity"): "trace",
    ("MultiProcessTraceabilityEvents", "routing_paths"): "static",
    ("MultiProcessTraceabilityEvents", "station_statistics"): "aggregate",
    ("OEECalculator", "calculate_availability"): "aggregate",
    ("OEECalculator", "calculate_oee"): "aggregate",
    ("OEECalculator", "calculate_performance"): "aggregate",
    ("OEECalculator", "calculate_quality"): "aggregate",
    ("OperatorPerformanceTracking", "operator_comparison"): "aggregate",
    ("OperatorPerformanceTracking", "operator_efficiency"): "aggregate",
    ("OperatorPerformanceTracking", "production_by_operator"): "aggregate",
    ("OperatorPerformanceTracking", "quality_by_operator"): "aggregate",
    ("OrderTraceabilityEvents", "build_timeline"): "trace",
    ("OrderTraceabilityEvents", "current_status"): "static",
    ("OrderTraceabilityEvents", "lead_time"): "aggregate",
    ("OrderTraceabilityEvents", "station_dwell_statistics"): "aggregate",
    ("ValueTraceabilityEvents", "build_timeline"): "trace",
    ("ValueTraceabilityEvents", "current_status"): "static",
    ("ValueTraceabilityEvents", "lead_time"): "aggregate",
    ("ValueTraceabilityEvents", "station_dwell_statistics"): "aggregate",
    ("PartProductionTracking", "daily_production_summary"): "aggregate",
    ("PartProductionTracking", "production_by_part"): "aggregate",
    ("PartProductionTracking", "production_totals"): "aggregate",
    ("PerformanceLossTracking", "performance_by_shift"): "aggregate",
    ("PerformanceLossTracking", "performance_trend"): "aggregate",
    ("PerformanceLossTracking", "slow_periods"): "interval",
    ("PeriodSummary", "compare_periods"): "aggregate",
    ("PeriodSummary", "from_daily_data"): "aggregate",
    ("PeriodSummary", "monthly_summary"): "aggregate",
    ("PeriodSummary", "weekly_summary"): "aggregate",
    ("QualityTracking", "daily_quality_summary"): "aggregate",
    ("QualityTracking", "nok_by_reason"): "outcome",
    ("QualityTracking", "nok_by_shift"): "aggregate",
    ("QualityTracking", "quality_by_part"): "aggregate",
    ("ReworkTracking", "rework_by_reason"): "outcome",
    ("ReworkTracking", "rework_by_shift"): "aggregate",
    ("ReworkTracking", "rework_cost"): "aggregate",
    ("ReworkTracking", "rework_rate"): "aggregate",
    ("ReworkTracking", "rework_trend"): "aggregate",
    ("RoutingTraceabilityEvents", "build_routing_timeline"): "trace",
    ("RoutingTraceabilityEvents", "lead_time"): "aggregate",
    ("RoutingTraceabilityEvents", "routing_paths"): "static",
    ("RoutingTraceabilityEvents", "station_statistics"): "aggregate",
    ("RuntimeAccountingEvents", "operating_hours_meter"): "aggregate",
    ("RuntimeAccountingEvents", "runtime_per_window"): "aggregate",
    ("RuntimeAccountingEvents", "runtime_summary"): "aggregate",
    ("ScrapTracking", "scrap_by_reason"): "outcome",
    ("ScrapTracking", "scrap_by_shift"): "aggregate",
    ("ScrapTracking", "scrap_cost"): "aggregate",
    ("ScrapTracking", "scrap_trend"): "aggregate",
    ("SetupTimeTracking", "setup_by_product"): "aggregate",
    ("SetupTimeTracking", "setup_durations"): "interval",
    ("SetupTimeTracking", "setup_statistics"): "aggregate",
    ("SetupTimeTracking", "setup_trend"): "aggregate",
    ("ShiftHandoverReport", "from_shift_data"): "aggregate",
    ("ShiftHandoverReport", "generate_report"): "aggregate",
    ("ShiftReporting", "best_and_worst_shifts"): "aggregate",
    ("ShiftReporting", "shift_comparison"): "aggregate",
    ("ShiftReporting", "shift_production"): "aggregate",
    ("ShiftReporting", "shift_targets"): "aggregate",
    ("TargetTracking", "compare_to_target"): "aggregate",
    ("TargetTracking", "target_achievement_summary"): "aggregate",
    # ---- quality -----------------------------------------------------------
    ("AnomalyClassificationEvents", "classify_anomalies"): "outcome",
    ("AnomalyClassificationEvents", "detect_drift"): "threshold",
    ("AnomalyClassificationEvents", "detect_flatline"): "interval",
    ("AnomalyClassificationEvents", "detect_oscillation"): "interval",
    ("CapabilityTrendingEvents", "capability_forecast"): "forecast",
    ("CapabilityTrendingEvents", "capability_over_time"): "aggregate",
    ("CapabilityTrendingEvents", "detect_capability_drop"): "threshold",
    ("CapabilityTrendingEvents", "yield_estimate"): "forecast",
    ("DataGapAnalysisEvents", "coverage_by_period"): "aggregate",
    ("DataGapAnalysisEvents", "find_gaps"): "interval",
    ("DataGapAnalysisEvents", "gap_summary"): "aggregate",
    ("DataGapAnalysisEvents", "interpolation_candidates"): "outcome",
    ("GaugeRepeatabilityEvents", "gauge_rr_summary"): "static",
    ("GaugeRepeatabilityEvents", "measurement_bias"): "static",
    ("GaugeRepeatabilityEvents", "repeatability"): "static",
    ("GaugeRepeatabilityEvents", "reproducibility"): "static",
    ("MultiSensorValidationEvents", "consensus_score"): "aggregate",
    ("MultiSensorValidationEvents", "detect_disagreement"): "threshold",
    ("MultiSensorValidationEvents", "identify_outlier_sensor"): "static",
    ("MultiSensorValidationEvents", "pairwise_bias"): "static",
    ("OutlierDetectionEvents", "detect_outliers_iqr"): "threshold",
    ("OutlierDetectionEvents", "detect_outliers_isolation_forest"): "threshold",
    ("OutlierDetectionEvents", "detect_outliers_mad"): "threshold",
    ("OutlierDetectionEvents", "detect_outliers_zscore"): "threshold",
    ("SensorDriftEvents", "calibration_health"): "aggregate",
    ("SensorDriftEvents", "detect_span_drift"): "threshold",
    ("SensorDriftEvents", "detect_zero_drift"): "threshold",
    ("SensorDriftEvents", "drift_trend"): "aggregate",
    ("SignalQualityEvents", "data_completeness"): "aggregate",
    ("SignalQualityEvents", "detect_missing_data"): "interval",
    ("SignalQualityEvents", "detect_out_of_range"): "threshold",
    ("SignalQualityEvents", "sampling_regularity"): "aggregate",
    ("StatisticalProcessControlRuleBased", "apply_rules_vectorized"): "threshold",
    ("StatisticalProcessControlRuleBased", "calculate_control_limits"): "static",
    (
        "StatisticalProcessControlRuleBased",
        "calculate_dynamic_control_limits",
    ): "aggregate",
    ("StatisticalProcessControlRuleBased", "detect_cusum_shifts"): "threshold",
    ("StatisticalProcessControlRuleBased", "interpret_violations"): "outcome",
    ("StatisticalProcessControlRuleBased", "process"): "threshold",
    ("StatisticalProcessControlRuleBased", "rule_1"): "threshold",
    ("StatisticalProcessControlRuleBased", "rule_2"): "threshold",
    ("StatisticalProcessControlRuleBased", "rule_3"): "threshold",
    ("StatisticalProcessControlRuleBased", "rule_4"): "threshold",
    ("StatisticalProcessControlRuleBased", "rule_5"): "threshold",
    ("StatisticalProcessControlRuleBased", "rule_6"): "threshold",
    ("StatisticalProcessControlRuleBased", "rule_7"): "threshold",
    ("StatisticalProcessControlRuleBased", "rule_8"): "threshold",
    ("ToleranceDeviationEvents", "process_and_group_data_with_events"): "threshold",
    ("ValueDistributionEvents", "detect_bimodal"): "aggregate",
    ("ValueDistributionEvents", "detect_mode_changes"): "threshold",
    ("ValueDistributionEvents", "normality_windows"): "aggregate",
    ("ValueDistributionEvents", "percentile_tracking"): "aggregate",
    # ---- supplychain -------------------------------------------------------
    ("DemandPatternEvents", "demand_by_period"): "aggregate",
    ("DemandPatternEvents", "detect_demand_spikes"): "threshold",
    ("DemandPatternEvents", "seasonality_summary"): "static",
    ("InventoryMonitoringEvents", "consumption_rate"): "aggregate",
    ("InventoryMonitoringEvents", "detect_low_stock"): "threshold",
    ("InventoryMonitoringEvents", "reorder_point_breach"): "threshold",
    ("InventoryMonitoringEvents", "stockout_prediction"): "forecast",
    ("LeadTimeAnalysisEvents", "calculate_lead_times"): "interval",
    ("LeadTimeAnalysisEvents", "detect_lead_time_anomalies"): "threshold",
    ("LeadTimeAnalysisEvents", "lead_time_statistics"): "aggregate",
}
